#! /bin/sh /usr/share/dpatch/dpatch-run
## 30_backport_dropping_panasonic_ids.dpatch by Cyril Brulebois <kibi@debian.org>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: Disable some buggy Panasonic IDs (04da:2372) to ensure those cameras can
## DP: be used as mass-storage devices (Closes: #479135, #482848).

@DPATCH@

--- a/camlibs/ptp2/library.c
+++ b/camlibs/ptp2/library.c
@@ -561,15 +561,12 @@
 	{"Panasonic:DMC-FZ20 (alternate id)", 0x04da, 0x2372, 0},
 	*/
 	/* http://sourceforge.net/tracker/index.php?func=detail&aid=1350226&group_id=8874&atid=208874 */
-	{"Panasonic:DMC-LZ2",             0x04da, 0x2372, 0},
 	/* https://sourceforge.net/tracker/index.php?func=detail&aid=1405541&group_id=8874&atid=358874 */
-	{"Panasonic:DMC-LC1",             0x04da, 0x2372, 0},
 
 	/* Søren Krarup Olesen <sko@acoustics.aau.dk> */
 	{"Leica:D-LUX 2",                 0x04da, 0x2375, 0},
 
 	/* http://sourceforge.net/tracker/index.php?func=detail&aid=1275100&group_id=8874&atid=358874 */
-	{"Panasonic:Lumix FZ5",           0x04da, 0x2372, 0},
 
 	{"Panasonic:DMC-FZ20",            0x04da, 0x2374, 0},
 	{"Panasonic:DMC-FZ50",            0x04da, 0x2374, 0},
